server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/verdugox/ms-config-repository.git
          clone-on-start: true
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/verdugox/ms-config-repository.git
#          default-label: main

